version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8123:8123"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped




#sudo ln -s /etc/nginx/sites-available/backendrocketmain /etc/nginx/sites-enabled
